[server]
ip = "0.0.0.0"
port = 56789

    [server.vertify]
    signingKey = "simver"
    visitCounts = 100
    checkCounts = 1
    expiredTime = 86400000000000

    [server.rpc]
    ip = "0.0.0.0"
    port = 56780

[databases]
    [databases.redis]
    ip = "127.0.0.1"
    port = 6379
    password = ""
    db = 0

[middlewares]

    [middlewares.cors]
    active = true
    allowOrigins = ["*"]
    allowMethods = ["GET", "HEAD", "PUT", "PATCH", "POST", "DELETE"]

    [middlewares.log]
    active = true
    format = "${time_rfc3339_nano} ${remote_ip} ${host} ${method} ${uri} ${status} ${latency_human} ${bytes_in} ${bytes_out}"
    output = "stdout"
